### PR TITLE
Add sharness tests

### PR DESCRIPTION
**Pull request by chriscool**
This is sharness support and a few basic tests to start a Standard Implementation Test Suite as discussed in issue #32.

go-multihash does not fully pass it for now because of things discussed in https://github.com/jbenet/go-multihash/issues/18.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This looks good as a basic 'set up sharness'. Do we want to enforce that all implementations implement the same set of subcommands

**Comment by chriscool** [comment]
I think o according to issue #32, sorry for not linking to it before.

**Comment by jbenet** [comment]
> Do we want to enforce that all implementations implement the same set of subcommands?

Yes, or at least a subset.

> I think so according to issue #32, sorry for not linking to it before.

Yep.

**Comment by jbenet** [comment]
This LGTM! 👍

**Comment by jbenet** [comment]
thanks @chriscool

**Pull request merged**
