### PR TITLE
Added a link to a .NET implementation of the multihash protocol

### PR DESCRIPTION
**Pull request by MCGPPeters**
I've created a .NET implementation of the multihash protocol. I've added a link to the readme.

### CODE REVIEW

**Comment by jbenet** [comment]
Sorry, can rebase? i merged another and markdown doesnt merge well. i will do it manually in a few days if not.

**Comment by MCGPPeters** [comment]
Np. Will do as soon as I am home later today...

**Comment by MCGPPeters** [comment]
Rebase done...

**Comment by jbenet** [comment]
I merged this, because it was outstanding. 

But could we rename it to "net-multihash", at least in the listing, to follow the convention? `<lang>-<thing>` is not always correct according to each `<lang>` but it makes for a cleaner `<thing>`.

**Pull request merged**
