### PR TITLE
replace ``sha3`` name with ``sha3-512``, add other SHA-3 functions

### PR DESCRIPTION
**Pull request by ivilata**
Now ``sha3`` should be used as a deprecated alias to ``sha3-512``. See issue #11 and PR #12.

### CODE REVIEW

**Comment by jbenet** [comment]
This LGTM. i will give some time for anyone to speak up against this.

**Comment by kofalt** [comment]
Definitely prefer this :+1:

**Comment by candeira** [comment]
+1

**Comment by jbenet** [comment]
boom!

**Comment by jbenet** [comment]
### Compatibility Note

Make sure to keep the string code `sha3` as an alias for `sha3-512`

**Pull request merged**
